spring:

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 52.78.6.152
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG            # 실행되는 SQL 쿼리 로그 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # 바인딩된 파라미터 값 출력
    org.springframework.orm.jpa: DEBUG  # JPA 설정 및 트랜잭션 처리 로그
    org.springframework.transaction: DEBUG # 트랜잭션 시작/커밋 로그
    com.zaxxer.hikari: DEBUG            # HikariCP 커넥션 풀 로그

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800}