name: deploy.yml
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

#      - name: Install Gradle wrapper
#        run: |
#          chmod +x ./script/sh/install-gradle-wrapper.sh
#          ./script/sh/install-gradle-wrapper.sh 8.14

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/test-results/test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t baseball-api:dev .

      - name: Tag Docker image
        run: docker tag baseball-api:dev ${{ secrets.DOCKERHUB_USERNAME }}/baseball-api:dev

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/baseball-api:dev

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo bash deploy.sh
